---
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: 
  database: squash_me
test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password:
  database: squash_me
production:
  adapter: postgresql
  encoding: utf8
  host: 
  username: postgres
  password: 
  database: squash_me
  pool: 30
