# postgres://vsgclcxrdidxuf:1gl7lNnByy4czj1rHDSgvnHJ_y@ec2-54-225-239-184.compute-1.amazonaws.com:5432/datos8d63brms0
---
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: 
  database: squash_me
test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password:
  database: squash_me
production:
  adapter: postgresql
  encoding: utf8
  host: 
  username: postgres
  password: 
  database: squash_me
  pool: 30
